// users
export const REQUEST_CURRENT_USER_SUCCESS = 'REQUEST_CURRENT_USER_SUCCESS';
export const REQUEST_CURRENT_USER_FAILURE = 'REQUEST_CURRENT_USER_FAILURE';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

// authentication
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILURE = 'REQUEST_LOGIN_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

// dealership
export const REQUEST_DEALERSHIPS_SUCCESS = 'REQUEST_DEALERSHIPS_SUCCESS';
export const REQUEST_DEALERSHIPS_FAILURE = 'REQUEST_DEALERSHIPS_FAILURE';
export const CREATE_DEALERSHIP_SUCCESS = 'CREATE_DEALERSHIP_SUCCESS';
export const CREATE_DEALERSHIP_FAILURE = 'CREATE_DEALERSHIP_FAILURE';
export const UPDATE_DEALERSHIP_SUCCESS = 'UPDATE_DEALERSHIP_SUCCESS';
export const UPDATE_DEALERSHIP_FAILURE = 'UPDATE_DEALERSHIP_FAILURE';
export const DELETE_DEALERSHIP_SUCCESS = 'DELETE_DEALERSHIP_SUCCESS';
export const DELETE_DEALERSHIP_FAILURE = 'DELETE_DEALERSHIP_FAILURE';
export const GENERATE_API_SUCCESS = 'GENERATE_API_SUCCESS';
export const GENERATE_API_FAILURE = 'GENERATE_API_FAILURE';
export const SELECTED_DEALERSHIP = 'SELECTED_DEALERSHIP';

// review
export const REQUEST_REVIEWS_SUCCESS = 'REQUEST_REVIEWS_SUCCESS';
export const REQUEST_REVIEWS_FAILURE = 'REQUEST_REVIEWS_FAILURE';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAILURE = 'CREATE_REVIEW_FAILURE';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_FAILURE = 'UPDATE_REVIEW_FAILURE';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAILURE = 'DELETE_REVIEW_FAILURE';
export const CREATE_REVIEW_FROM_IFRAME_SUCCESS = 'CREATE_REVIEW_FROM_IFRAME_SUCCESS';
export const CREATE_REVIEW_FROM_IFRAME_FAILURE = 'CREATE_REVIEW_FROM_IFRAME_FAILURE';